#!/bin/bash
# Delete bad episodes - generated by check_episodes.py
cd /home/iml/RockyEVO/data/raw/xtrainer_pin_v2_debug/collect_data
echo 'The following episodes will be deleted:'
echo '  20260919174130'
echo '  20260919174252'
echo '  20260919174345'
echo '  20260919174500'
echo ''
read -p 'Confirm deletion? (y/N): ' confirm
if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    rm -rf 20260919174130
    rm -rf 20260919174252
    rm -rf 20260919174345
    rm -rf 20260919174500
    echo "Deleted successfully."
else
    echo "Cancelled."
fi
